name: 网易云飞升

on:
  schedule:
    - cron: "0 4/16 * * *"
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Script
        env:
          PHONE: ${{ secrets.PHONE }}
          PASSWORD_PLAIN: ${{ secrets.PASSWORD_PLAIN }}
          SC_KEY: ${{ secrets.SC_KEY }}
        run: |
          if [ ${PASSWORD_PLAIN} ]; then PASSWORD=$PASSWORD_PLAIN; fi
          if [ ${SC_KEY} ];then SC_CMD="-s $SC_KEY"; fi
          python3 action.py ${PHONE} ${SC_CMD}
